# Generated by Django 2.2 on 2019-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bataloguser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='bataloguser',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='bataloguser',
            table=None,
        ),
    ]
